### ISSUE TITLE
Solution and Project Skeleton

### ISSUE THREAD

**Issue by derrysmith** [derrysmith/Socially#1]
As a software developer, I would like to have the shells of the applications and supporting libraries defined in the repository, so that I can easily start developing features.

- [x] Create Socially solution
- [x] Create Socially.Core class library project
- [x] Create Socially.Core.Tests test project
- [x] Create Socially.Api NancyFx project
- [x] Create Socially.Api.Tests test project
- [ ] Create Socially.App Cordova project
- [x] Create Socially.App.Tests test project
- [x] Create Socially.Web ASP.NET MVC project
- [x] Create Socially.Web.Tests test project
- [ ] Configure MSpec Runners for test projects
