### ISSUE TITLE
Configure Appharbor

### ISSUE THREAD

**Issue by derrysmith** [derrysmith/Socially#2]
As a user, I would like to be able to locate the applications by URL, so that I can utilize the site's features.

- [ ] Create Appharbor applications for Socially.Api (prod & qa)
- [ ] Create Appharbor applications for Socially.App (prod & qa)
- [ ] Create Appharbor applications for Socially.Web (prod & qa)
